# Generated by Django 2.0.7 on 2018-07-30 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailies', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contractors',
            new_name='Contractor',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
