# Generated by Django 2.0.7 on 2018-07-30 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailies', '0003_auto_20180730_1559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='project',
            new_name='project_id',
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together=set(),
        ),
    ]
