# Generated by Django 2.0.7 on 2018-07-30 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailies', '0004_auto_20180730_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(max_length=25, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='labor_class',
            field=models.CharField(max_length=10, verbose_name='Labor Class'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(max_length=25, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='employee_report',
            name='task_details',
            field=models.TextField(verbose_name='Task Details'),
        ),
        migrations.AlterField(
            model_name='employee_report',
            name='task_hours',
            field=models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Task Hours'),
        ),
        migrations.AlterField(
            model_name='employee_report',
            name='task_name',
            field=models.CharField(max_length=100, verbose_name='Task Name'),
        ),
        migrations.AlterField(
            model_name='equipment_report',
            name='hours_used',
            field=models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Hours Used'),
        ),
        migrations.AlterField(
            model_name='project',
            name='number',
            field=models.IntegerField(verbose_name='Project Number'),
        ),
        migrations.AlterField(
            model_name='report',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Report id'),
        ),
    ]
