# Generated by Django 2.0.7 on 2018-07-31 01:45

from django.db import migrations, models
import django.db.models.deletion
import django.views.generic.base


class Migration(migrations.Migration):

    dependencies = [
        ('dailies', '0006_auto_20180730_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportView',
            fields=[
                ('report_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dailies.Report')),
            ],
            bases=(django.views.generic.base.TemplateView, 'dailies.report'),
        ),
    ]
