# Generated by Django 2.0.7 on 2018-08-05 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailies', '0007_reportview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee_report',
            old_name='employee_id',
            new_name='employee',
        ),
        migrations.RenameField(
            model_name='employee_report',
            old_name='report_id',
            new_name='report',
        ),
        migrations.RenameField(
            model_name='equipment_report',
            old_name='equipment_id',
            new_name='equipment',
        ),
        migrations.RenameField(
            model_name='equipment_report',
            old_name='report_id',
            new_name='report',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='project_id',
            new_name='project',
        ),
    ]
