# Generated by Django 2.0.5 on 2018-08-28 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailies', '0008_auto_20180804_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportview',
            name='report_ptr',
        ),
        migrations.AddField(
            model_name='report',
            name='user_pk',
            field=models.IntegerField(default=1, verbose_name='User PK'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ReportView',
        ),
    ]
